variables:
    BUILD_CONCURRENCY: "10"

stages:
  - build
  - package

cache:
    paths: &cache-paths
    - build

.windows-cache-spec-template: &windows-cache-spec
    cache:
        paths: *cache-paths
        key: "%CI_BUILD_NAME%/%CI_BUILD_REF_NAME%/%CI_RUNNER_ID%"

.artifacts-spec-build-template: &artifact-spec-build
    artifacts:
        name: "mce_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}_${CI_BUILD_REF}_${CI_BUILD_NAME}"
        expire_in: 1 week
        paths:
        - ${BUILD_COMPILER_NAME}

.gmake-build-template: &gmake-build-task
    stage: build
    script:
    - cmake -E make_directory build
    - cd build
    - cmake -G "${BUILD_GENERATOR}" -DCMAKE_C_COMPILER=${BUILD_C_COMPILER} -DCMAKE_CXX_COMPILER=${BUILD_CXX_COMPILER} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
    - cmake --build . -- -j ${BUILD_CONCURRENCY}
    - cd ..
    - cmake -E make_directory ${BUILD_COMPILER_NAME}
    - cmake -E rename build/multicore_engine_core_tests/multicore_engine_core_tests${BUILD_EXE_SUFFIX} ${BUILD_COMPILER_NAME}/core_tests${BUILD_EXE_SUFFIX}
    - cmake -E rename build/multicore_engine_demo/multicore_engine_demo${BUILD_EXE_SUFFIX} ${BUILD_COMPILER_NAME}/demo${BUILD_EXE_SUFFIX}
    - cmake -E rename build/multicore_engine_load_unit_gen/multicore_engine_load_unit_gen${BUILD_EXE_SUFFIX} ${BUILD_COMPILER_NAME}/load_unit_gen${BUILD_EXE_SUFFIX}
    - cmake -E rename build/multicore_engine_pack_file_gen/multicore_engine_pack_file_gen${BUILD_EXE_SUFFIX} ${BUILD_COMPILER_NAME}/pack_file_gen${BUILD_EXE_SUFFIX}
    #- cmake -E rename build/multicore_engine_assets/assets.pack ${BUILD_COMPILER_NAME}/assets.pack
    - cmake -E chdir . ${BUILD_COMPILER_NAME}/core_tests${BUILD_EXE_SUFFIX} --report_level=short

.msbuild-build-template: &msbuild-build-task
    stage: build
    script:
    - cmake -E make_directory build
    - cd build
    - cmake -G "${BUILD_GENERATOR}" ..
    - cmake --build . --config ${BUILD_TYPE}
    - cd ..
    - cmake -E make_directory ${BUILD_COMPILER_NAME}
    - cmake -E rename build/multicore_engine_core_tests/${BUILD_TYPE}/multicore_engine_core_tests${BUILD_EXE_SUFFIX} ${BUILD_COMPILER_NAME}/core_tests${BUILD_EXE_SUFFIX}
    - cmake -E rename build/multicore_engine_demo/${BUILD_TYPE}/multicore_engine_demo${BUILD_EXE_SUFFIX} ${BUILD_COMPILER_NAME}/demo${BUILD_EXE_SUFFIX}
    - cmake -E rename build/multicore_engine_load_unit_gen/${BUILD_TYPE}/multicore_engine_load_unit_gen${BUILD_EXE_SUFFIX} ${BUILD_COMPILER_NAME}/load_unit_gen${BUILD_EXE_SUFFIX}
    - cmake -E rename build/multicore_engine_pack_file_gen/${BUILD_TYPE}/multicore_engine_pack_file_gen${BUILD_EXE_SUFFIX} ${BUILD_COMPILER_NAME}/pack_file_gen${BUILD_EXE_SUFFIX}
    #- cmake -E rename build/multicore_engine_assets/${BUILD_TYPE}/assets.pack ${BUILD_COMPILER_NAME}/assets.pack
    - cmake -E chdir . ${BUILD_COMPILER_NAME}/core_tests${BUILD_EXE_SUFFIX} --report_level=short

.package-task-template: &package-task
    stage: package
    variables:
        GIT_STRATEGY: none
    script:
    - sha1sum -b cloc_report.txt refman.pdf gcc/* clang/* msvc/* mingw/* > checksums.txt
    - cat checksums.txt
    tags:
    - package
    artifacts:
        name: "mce_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}_${CI_BUILD_REF}"
        paths:
        - refman.pdf
        - cloc_report.txt
        - gcc
        - clang
        - msvc
        - mingw
        - checksums.txt

gcc-debug-build:
    variables:
        BUILD_CXX_COMPILER: "g++"
        BUILD_C_COMPILER: "gcc"
        BUILD_TYPE: "Debug"
        BUILD_COMPILER_NAME: "gcc"
        BUILD_GENERATOR: "Unix Makefiles"
        BUILD_EXE_SUFFIX: ""
    tags:
    - cpp
    <<: *gmake-build-task

gcc-release-build:
    variables:
        BUILD_CXX_COMPILER: "g++"
        BUILD_C_COMPILER: "gcc"
        BUILD_TYPE: "Release"
        BUILD_COMPILER_NAME: "gcc"
        BUILD_GENERATOR: "Unix Makefiles"
        BUILD_EXE_SUFFIX: ""
    tags:
    - cpp
    <<: *gmake-build-task
    <<: *artifact-spec-build

clang-debug-build:
    variables:
        BUILD_CXX_COMPILER: "clang++"
        BUILD_C_COMPILER: "clang"
        BUILD_TYPE: "Debug"
        BUILD_COMPILER_NAME: "clang"
        BUILD_GENERATOR: "Unix Makefiles"
        BUILD_EXE_SUFFIX: ""
    tags:
    - cpp
    <<: *gmake-build-task

clang-release-build:
    variables:
        BUILD_CXX_COMPILER: "clang++"
        BUILD_C_COMPILER: "clang"
        BUILD_TYPE: "Release"
        BUILD_COMPILER_NAME: "clang"
        BUILD_GENERATOR: "Unix Makefiles"
        BUILD_EXE_SUFFIX: ""
    tags:
    - cpp
    <<: *gmake-build-task
    <<: *artifact-spec-build

msvc-debug-build:
    variables:
        BUILD_COMPILER_NAME: "msvc"
        BUILD_TYPE: "Debug"
        BUILD_GENERATOR: "Visual Studio 14 2015 Win64"
        BUILD_EXE_SUFFIX: ".exe"
    tags:
    - win-cpp
    <<: *msbuild-build-task
    <<: *windows-cache-spec    

msvc-release-build:
    variables:
        BUILD_COMPILER_NAME: "msvc"
        BUILD_TYPE: "Release"
        BUILD_GENERATOR: "Visual Studio 14 2015 Win64"
        BUILD_EXE_SUFFIX: ".exe"
    tags:
    - win-cpp
    <<: *msbuild-build-task
    <<: *windows-cache-spec    
    <<: *artifact-spec-build

mingw-debug-build:
    variables:
        BUILD_CXX_COMPILER: "g++"
        BUILD_C_COMPILER: "gcc"
        BUILD_TYPE: "Debug"
        BUILD_COMPILER_NAME: "mingw"
        BUILD_GENERATOR: "MinGW Makefiles"
        BUILD_EXE_SUFFIX: ".exe"
    tags:
    - win-cpp
    <<: *gmake-build-task
    <<: *windows-cache-spec

mingw-release-build:
    variables:
        BUILD_CXX_COMPILER: "g++"
        BUILD_C_COMPILER: "gcc"
        BUILD_TYPE: "Release"
        BUILD_COMPILER_NAME: "mingw"
        BUILD_GENERATOR: "MinGW Makefiles"
        BUILD_EXE_SUFFIX: ".exe"
    tags:
    - win-cpp
    <<: *gmake-build-task
    <<: *artifact-spec-build
    <<: *windows-cache-spec

cpp-check:
  stage: build
  script:
  - cppcheck -j 8 -v --inline-suppr --enable=all -I multicore_engine_base/include/ -I multicore_engine_core/include/ .
  tags:
  - cpp
  
scan-build:
  stage: build
  script:
  - mkdir -p build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug -DSTATIC_ANALYSIS_ONLY=YES ..
  - scan-build --status-bugs make -j $[$(grep -c ^processor /proc/cpuinfo)+2] config=debug CC=clang CXX=clang++
  tags:
  - cpp

api-doc:
  stage: build
  script:
  - chmod +x generate_cloc_report.sh
  - ./generate_cloc_report.sh
  - doxygen Doxyfile
  - cd doc/latex
  - pdflatex refman.tex
  - makeindex refman
  - pdflatex refman.tex
  - pdflatex refman.tex
  - mv refman.pdf ../..
  tags:
  - latex
  - doxygen
  artifacts:
    name: "mce_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}_${CI_BUILD_REF}_${CI_BUILD_NAME}"
    expire_in: 1 week
    paths:
    - refman.pdf
    - cloc_report.txt

package-base:
    <<: *package-task
    except: 
    - tags
    artifacts:
        expire_in: 6 months

package-tags:
    <<: *package-task
    only: 
    - tags

