stages:
  - analyse
  - build

scan-build:
  stage: analyse
  script:
  - premake5 --cc=gcc gmake
  - make config=debug clean
  - make config=release clean
  - export CC=clang
  - export CXX=clang++
  - scan-build --status-bugs make -j 6 config=debug CC=clang CXX=clang++

gcc-build:
  stage: build
  script:
  - premake5 --cc=gcc gmake
  - export CC=gcc
  - export CXX=g++
  - make CC=gcc CXX=g++ config=debug clean
  - make CC=gcc CXX=g++ config=release clean
  - make -j 6 config=debug CC=gcc CXX=g++
  - make -j 6 config=release CC=gcc CXX=g++
  - multicore_engine_core_tests/build/bin-gcc/debug/multicore_engine_core_tests --report_level=short
  - multicore_engine_core_tests/build/bin-gcc/release/multicore_engine_core_tests --report_level=short

clang-build:
  stage: build
  script:
  - premake5 --cc=clang gmake
  - export CC=clang
  - export CXX=clang++
  - make CC=clang CXX=clang++ config=debug clean
  - make CC=clang CXX=clang++ config=release clean
  - make -j 6 config=debug CC=clang CXX=clang++
  - make -j 6 config=release CC=clang CXX=clang++
  - multicore_engine_core_tests/build/bin-clang/debug/multicore_engine_core_tests --report_level=short
  - multicore_engine_core_tests/build/bin-clang/release/multicore_engine_core_tests --report_level=short

