before_script:
  - premake5 --cc=gcc gmake > /dev/null
  - make CC=gcc CXX=g++ config=debug clean > /dev/null
  - make CC=gcc CXX=g++ config=release clean > /dev/null
  - premake5 --cc=clang gmake > /dev/null
  - make CC=clang CXX=clang++ config=debug clean > /dev/null
  - make CC=clang CXX=clang++ config=release clean > /dev/null
  - mkdir -p multicore_engine_{core,core_tests,demo,parsers,load_unit_gen,pack_file_gen}/build/{bin,obj-{gcc,clang}-{debug,release}}

#stages:
#  - analyse
#  - build_and_test

scan-build:
#  stage: analyse
  script:
  - premake5 --cc=gcc gmake
  - export CC=clang
  - export CXX=clang++
  - scan-build --status-bugs make -j $[$(grep -c ^processor /proc/cpuinfo)*2] config=debug CC=clang CXX=clang++
  tags:
  - cpp

gcc-debug-build:
#  stage: build_and_test
  script:
  - premake5 --cc=gcc gmake
  - export CC=gcc
  - export CXX=g++
  - make -j $[$(grep -c ^processor /proc/cpuinfo)*2] config=debug CC=gcc CXX=g++
  - multicore_engine_core_tests/build/bin/multicore_engine_core_tests-gcc-debug --report_level=short
  tags:
  - cpp

gcc-release-build:
#  stage: build_and_test
  script:
  - premake5 --cc=gcc gmake
  - export CC=gcc
  - export CXX=g++
  - make -j $[$(grep -c ^processor /proc/cpuinfo)*2] config=release CC=gcc CXX=g++
  - multicore_engine_core_tests/build/bin/multicore_engine_core_tests-gcc-release --report_level=short
  tags:
  - cpp

clang-debug-build:
#  stage: build_and_test
  script:
  - premake5 --cc=clang gmake
  - export CC=clang
  - export CXX=clang++
  - make -j $[$(grep -c ^processor /proc/cpuinfo)*2] config=debug CC=clang CXX=clang++
  - multicore_engine_core_tests/build/bin/multicore_engine_core_tests-clang-debug --report_level=short
  tags:
  - cpp

clang-release-build:
#  stage: build_and_test
  script:
  - premake5 --cc=clang gmake
  - export CC=clang
  - export CXX=clang++
  - make -j $[$(grep -c ^processor /proc/cpuinfo)*2] config=release CC=clang CXX=clang++
  - multicore_engine_core_tests/build/bin/multicore_engine_core_tests-clang-release --report_level=short
  tags:
  - cpp
