before_script:
  - mkdir -p multicore_engine_{core,core_tests,demo,parsers,load_unit_gen,pack_file_gen}/build/{bin,obj-{gcc,clang}-{debug,release}}

scan-build:
  script:
  - premake5 --cc=gcc gmake
  - export CC=clang
  - export CXX=clang++
  - scan-build --status-bugs make -j $[$(grep -c ^processor /proc/cpuinfo)*2] config=debug CC=clang CXX=clang++
  tags:
  - cpp

gcc-debug-build:
  script:
  - premake5 --cc=gcc gmake
  - export CC=gcc
  - export CXX=g++
  - make -j $[$(grep -c ^processor /proc/cpuinfo)*2] config=debug CC=gcc CXX=g++
  - multicore_engine_core_tests/build/bin/multicore_engine_core_tests-gcc-debug --report_level=short
  tags:
  - cpp
  artifacts:
    paths:
    - */build/bin/

gcc-release-build:
  script:
  - premake5 --cc=gcc gmake
  - export CC=gcc
  - export CXX=g++
  - make -j $[$(grep -c ^processor /proc/cpuinfo)*2] config=release CC=gcc CXX=g++
  - multicore_engine_core_tests/build/bin/multicore_engine_core_tests-gcc-release --report_level=short
  tags:
  - cpp
  artifacts:
    paths:
    - */build/bin/

clang-debug-build:
  script:
  - premake5 --cc=clang gmake
  - export CC=clang
  - export CXX=clang++
  - make -j $[$(grep -c ^processor /proc/cpuinfo)*2] config=debug CC=clang CXX=clang++
  - multicore_engine_core_tests/build/bin/multicore_engine_core_tests-clang-debug --report_level=short
  tags:
  - cpp
  artifacts:
    paths:
    - */build/bin/

clang-release-build:
  script:
  - premake5 --cc=clang gmake
  - export CC=clang
  - export CXX=clang++
  - make -j $[$(grep -c ^processor /proc/cpuinfo)*2] config=release CC=clang CXX=clang++
  - multicore_engine_core_tests/build/bin/multicore_engine_core_tests-clang-release --report_level=short
  tags:
  - cpp
  artifacts:
    paths:
    - */build/bin/

api-doc:
  script:
  - doxygen Doxyfile
  - cd doc/latex
  - pdflatex refman.tex
#  - bibtex refman
  - makeindex refman
  - pdflatex refman.tex
  - pdflatex refman.tex
  - mv refman.pdf ..
  tags:
  - latex
  - doxygen
  artifacts:
    paths:
    - doc/html
    - doc/refman.pdf

