stages:
  - build
  - deploy

scan-build:
  stage: build
  script:
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug -DSTATIC_ANALYSIS_ONLY=YES ..
  - scan-build --status-bugs make -j $[$(grep -c ^processor /proc/cpuinfo)+2] config=debug CC=clang CXX=clang++
  tags:
  - cpp

gcc-debug-build:
  stage: build
  script:
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Debug ..
  - make -j $[$(grep -c ^processor /proc/cpuinfo)+2]
  - cd ..
  - mv build/multicore_engine_core_tests/multicore_engine_core_tests core_tests-gcc-debug
  - mv build/multicore_engine_demo/multicore_engine_demo demo-gcc-debug
  - mv build/multicore_engine_load_unit_gen/multicore_engine_load_unit_gen load_unit_gen-gcc-debug
  - mv build/multicore_engine_pack_file_gen/multicore_engine_pack_file_gen pack_file_gen-gcc-debug
  - ./core_tests-gcc-debug --report_level=short
  tags:
  - cpp

gcc-release-build:
  stage: build
  script:
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release ..
  - make -j $[$(grep -c ^processor /proc/cpuinfo)+2]
  - cd ..
  - mv build/multicore_engine_core_tests/multicore_engine_core_tests core_tests-gcc-release
  - mv build/multicore_engine_demo/multicore_engine_demo demo-gcc-release
  - mv build/multicore_engine_load_unit_gen/multicore_engine_load_unit_gen load_unit_gen-gcc-release
  - mv build/multicore_engine_pack_file_gen/multicore_engine_pack_file_gen pack_file_gen-gcc-release
  - ./core_tests-gcc-release --report_level=short
  tags:
  - cpp
  artifacts:
    name: "mce_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}_${CI_BUILD_REF}_${CI_BUILD_NAME}"
    paths:
    - demo-gcc-release
    - load_unit_gen-gcc-release
    - pack_file_gen-gcc-release

clang-debug-build:
  stage: build
  script:
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug ..
  - make -j $[$(grep -c ^processor /proc/cpuinfo)+2]
  - cd ..
  - mv build/multicore_engine_core_tests/multicore_engine_core_tests core_tests-clang-debug
  - mv build/multicore_engine_demo/multicore_engine_demo demo-clang-debug
  - mv build/multicore_engine_load_unit_gen/multicore_engine_load_unit_gen load_unit_gen-clang-debug
  - mv build/multicore_engine_pack_file_gen/multicore_engine_pack_file_gen pack_file_gen-clang-debug
  - ./core_tests-clang-debug --report_level=short
  tags:
  - cpp

clang-release-build:
  stage: build
  script:
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release ..
  - make -j $[$(grep -c ^processor /proc/cpuinfo)+2]
  - cd ..
  - mv build/multicore_engine_core_tests/multicore_engine_core_tests core_tests-clang-release
  - mv build/multicore_engine_demo/multicore_engine_demo demo-clang-release
  - mv build/multicore_engine_load_unit_gen/multicore_engine_load_unit_gen load_unit_gen-clang-release
  - mv build/multicore_engine_pack_file_gen/multicore_engine_pack_file_gen pack_file_gen-clang-release
  - ./core_tests-clang-release --report_level=short
  tags:
  - cpp
  artifacts:
    name: "mce_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}_${CI_BUILD_REF}_${CI_BUILD_NAME}"
    paths:
    - demo-clang-release
    - load_unit_gen-clang-release
    - pack_file_gen-clang-release

api-doc:
  stage: build
  script:
  - chmod +x generate_cloc_report.sh
  - ./generate_cloc_report.sh
  - doxygen Doxyfile
  - cd doc/latex
  - pdflatex refman.tex
  - makeindex refman
  - pdflatex refman.tex
  - pdflatex refman.tex
  - mv refman.pdf ../..
  - chmod +x generate_cloc_report.sh
  - ./generate_cloc_report.sh
  tags:
  - latex
  - doxygen
  artifacts:
    name: "mce_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}_${CI_BUILD_REF}_${CI_BUILD_NAME}"
    paths:
    - refman.pdf
    - cloc_report.txt

deploy-all:
  stage: deploy
  script:
  - mv demo-gcc-release demo-gcc
  - mv load_unit_gen-gcc-release load_unit_gen-gcc
  - mv pack_file_gen-gcc-release pack_file_gen-gcc
  - mv demo-clang-release demo-clang
  - mv load_unit_gen-clang-release load_unit_gen-clang
  - mv pack_file_gen-clang-release pack_file_gen-clang
  tags:
  - deploy
  artifacts:
    name: "mce_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}_${CI_BUILD_REF}"
    paths:
    - refman.pdf
    - demo-gcc
    - load_unit_gen-gcc
    - pack_file_gen-gcc
    - demo-clang
    - load_unit_gen-clang
    - pack_file_gen-clang
    - cloc_report.txt

