stages:
  - build
  - package

cache:
    paths:
        - build

cpp-check:
  stage: build
  script:
  - cppcheck -j 8 -v --inline-suppr --enable=all -I multicore_engine_base/include/ -I multicore_engine_core/include/ .
  tags:
  - cpp
  
scan-build:
  stage: build
  script:
  - mkdir -p build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug -DSTATIC_ANALYSIS_ONLY=YES ..
  - scan-build --status-bugs make -j $[$(grep -c ^processor /proc/cpuinfo)+2] config=debug CC=clang CXX=clang++
  tags:
  - cpp

gcc-debug-build:
  stage: build
  script:
  - mkdir -p build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Debug ..
  - make -j $[$(grep -c ^processor /proc/cpuinfo)+2]
  - cd ..
  - mv build/multicore_engine_core_tests/multicore_engine_core_tests core_tests-gcc-debug
  - mv build/multicore_engine_demo/multicore_engine_demo demo-gcc-debug
  - mv build/multicore_engine_load_unit_gen/multicore_engine_load_unit_gen load_unit_gen-gcc-debug
  - mv build/multicore_engine_pack_file_gen/multicore_engine_pack_file_gen pack_file_gen-gcc-debug
  - ./core_tests-gcc-debug --report_level=short
  tags:
  - cpp

gcc-release-build:
  stage: build
  script:
  - mkdir -p build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release ..
  - make -j $[$(grep -c ^processor /proc/cpuinfo)+2]
  - cd ..
  - mv build/multicore_engine_core_tests/multicore_engine_core_tests core_tests-gcc-release
  - mv build/multicore_engine_demo/multicore_engine_demo demo-gcc-release
  - mv build/multicore_engine_load_unit_gen/multicore_engine_load_unit_gen load_unit_gen-gcc-release
  - mv build/multicore_engine_pack_file_gen/multicore_engine_pack_file_gen pack_file_gen-gcc-release
#  - mv build/multicore_engine_assets/assets.pack assets-gcc-release.pack
  - ./core_tests-gcc-release --report_level=short
  tags:
  - cpp
  artifacts:
    name: "mce_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}_${CI_BUILD_REF}_${CI_BUILD_NAME}"
    expire_in: 1 week
    paths:
    - demo-gcc-release
    - load_unit_gen-gcc-release
    - pack_file_gen-gcc-release
#    - assets-gcc-release.pack

clang-debug-build:
  stage: build
  script:
  - mkdir -p build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug ..
  - make -j $[$(grep -c ^processor /proc/cpuinfo)+2]
  - cd ..
  - mv build/multicore_engine_core_tests/multicore_engine_core_tests core_tests-clang-debug
  - mv build/multicore_engine_demo/multicore_engine_demo demo-clang-debug
  - mv build/multicore_engine_load_unit_gen/multicore_engine_load_unit_gen load_unit_gen-clang-debug
  - mv build/multicore_engine_pack_file_gen/multicore_engine_pack_file_gen pack_file_gen-clang-debug
  - ./core_tests-clang-debug --report_level=short
  tags:
  - cpp

clang-release-build:
  stage: build
  script:
  - mkdir -p build && cd build
  - cmake -G "Unix Makefiles" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release ..
  - make -j $[$(grep -c ^processor /proc/cpuinfo)+2]
  - cd ..
  - mv build/multicore_engine_core_tests/multicore_engine_core_tests core_tests-clang-release
  - mv build/multicore_engine_demo/multicore_engine_demo demo-clang-release
  - mv build/multicore_engine_load_unit_gen/multicore_engine_load_unit_gen load_unit_gen-clang-release
  - mv build/multicore_engine_pack_file_gen/multicore_engine_pack_file_gen pack_file_gen-clang-release
#  - mv build/multicore_engine_assets/assets.pack assets-clang-release.pack
  - ./core_tests-clang-release --report_level=short
  tags:
  - cpp
  artifacts:
    name: "mce_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}_${CI_BUILD_REF}_${CI_BUILD_NAME}"
    expire_in: 1 week
    paths:
    - demo-clang-release
    - load_unit_gen-clang-release
    - pack_file_gen-clang-release
#    - assets-clang-release.pack

msvc-debug-build:
  stage: build
  script:
  - if not exist build mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config Debug
  - cd ..
  - move build\multicore_engine_core_tests\Debug\multicore_engine_core_tests.exe core_tests-msvc-debug.exe
  - move build\multicore_engine_demo\Debug\multicore_engine_demo.exe demo-msvc-debug.exe
  - move build\multicore_engine_load_unit_gen\Debug\multicore_engine_load_unit_gen.exe load_unit_gen-msvc-debug.exe
  - move build\multicore_engine_pack_file_gen\Debug\multicore_engine_pack_file_gen.exe pack_file_gen-msvc-debug.exe
#  - move build\multicore_engine_assets\Debug\assets.pack assets-msvc-debug.pack
  - core_tests-msvc-debug.exe --report_level=short
  tags:
  - win-cpp
  cache:
    key: "%CI_BUILD_NAME%/%CI_BUILD_REF_NAME%/%CI_RUNNER_ID%"

msvc-release-build:
  stage: build
  script:
  - if not exist build mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build . --config Release
  - cd ..
  - move build\multicore_engine_core_tests\Release\multicore_engine_core_tests.exe core_tests-msvc-release.exe
  - move build\multicore_engine_demo\Release\multicore_engine_demo.exe demo-msvc-release.exe
  - move build\multicore_engine_load_unit_gen\Release\multicore_engine_load_unit_gen.exe load_unit_gen-msvc-release.exe
  - move build\multicore_engine_pack_file_gen\Release\multicore_engine_pack_file_gen.exe pack_file_gen-msvc-release.exe
#  - move build\multicore_engine_assets\Release\assets.pack assets-msvc-release.pack
  - core_tests-msvc-release.exe --report_level=short
  tags:
  - win-cpp
  artifacts:
    name: "mce_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}_${CI_BUILD_REF}_${CI_BUILD_NAME}"
    expire_in: 1 week
    paths:
    - demo-msvc-release.exe
    - load_unit_gen-msvc-release.exe
    - pack_file_gen-msvc-release.exe
#    - assets-msvc-release.pack
  cache:
    key: "%CI_BUILD_NAME%/%CI_BUILD_REF_NAME%/%CI_RUNNER_ID%"
    
mingw-debug-build:
  stage: build
  script:
  - if not exist build mkdir build
  - cd build
  - cmake -G "MinGW Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . -- -j 16
  - cd ..
  - cmake -E rename build/multicore_engine_core_tests/multicore_engine_core_tests.exe core_tests-mingw-debug.exe
  - cmake -E rename build/multicore_engine_demo/multicore_engine_demo.exe demo-mingw-debug.exe
  - cmake -E rename build/multicore_engine_load_unit_gen/multicore_engine_load_unit_gen.exe load_unit_gen-mingw-debug.exe
  - cmake -E rename build/multicore_engine_pack_file_gen/multicore_engine_pack_file_gen.exe pack_file_gen-mingw-debug.exe
  - core_tests-mingw-debug.exe --report_level=short
  tags:
  - win-cpp
  cache:
    key: "%CI_BUILD_NAME%/%CI_BUILD_REF_NAME%/%CI_RUNNER_ID%"

mingw-release-build:
  stage: build
  script:
  - if not exist build mkdir build
  - cd build
  - cmake -G "MinGW Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . -- -j 16
  - cd ..
  - cmake -E rename build/multicore_engine_core_tests/multicore_engine_core_tests.exe core_tests-mingw-release.exe
  - cmake -E rename build/multicore_engine_demo/multicore_engine_demo.exe demo-mingw-release.exe
  - cmake -E rename build/multicore_engine_load_unit_gen/multicore_engine_load_unit_gen.exe load_unit_gen-mingw-release.exe
  - cmake -E rename build/multicore_engine_pack_file_gen/multicore_engine_pack_file_gen.exe pack_file_gen-mingw-release.exe
#  - cmake -E rename build/multicore_engine_assets/assets.pack assets-mingw-release.pack
  - core_tests-mingw-release.exe --report_level=short
  tags:
  - win-cpp
  artifacts:
    name: "mce_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}_${CI_BUILD_REF}_${CI_BUILD_NAME}"
    expire_in: 1 week
    paths:
    - demo-mingw-release.exe
    - load_unit_gen-mingw-release.exe
    - pack_file_gen-mingw-release.exe
#    - assets-mingw-release.pack
  cache:
    key: "%CI_BUILD_NAME%/%CI_BUILD_REF_NAME%/%CI_RUNNER_ID%"

api-doc:
  stage: build
  script:
  - chmod +x generate_cloc_report.sh
  - ./generate_cloc_report.sh
  - doxygen Doxyfile
  - cd doc/latex
  - pdflatex refman.tex
  - makeindex refman
  - pdflatex refman.tex
  - pdflatex refman.tex
  - mv refman.pdf ../..
  tags:
  - latex
  - doxygen
  artifacts:
    name: "mce_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}_${CI_BUILD_REF}_${CI_BUILD_NAME}"
    expire_in: 1 week
    paths:
    - refman.pdf
    - cloc_report.txt
    
license-pack-win:
    stage: build
    script:
    - mkdir licenses\windows
    - cd licenses\windows
    - mkdir Boost glfw gli glm TBB vulkan-hpp zlib
    - copy C:\Libs\Boost\LICENSE_1_0.txt Boost
    - copy C:\Libs\glfw\COPYING.txt glfw
    - copy C:\Libs\gli\copying.txt gli
    - copy C:\Libs\glm\copying.txt glm
    - copy C:\Libs\TBB\LICENSE TBB
    - copy C:\Libs\vulkan-hpp\LICENSE.txt vulkan-hpp
    - copy C:\Libs\zlib\README zlib
    tags:
    - win-cpp
    artifacts:
        name: "mce_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}_${CI_BUILD_REF}_${CI_BUILD_NAME}"
        expire_in: 1 week
        paths:
        - licenses
        
package-base:
  stage: package
  except: 
    - tags
  script:
  - mkdir gcc
  - mkdir clang
  - mkdir msvc
  - mkdir mingw
  - mv demo-gcc-release gcc/demo
  - mv load_unit_gen-gcc-release gcc/load_unit_gen
  - mv pack_file_gen-gcc-release gcc/pack_file_gen
#  - mv assets-gcc-release.pack gcc/assets.pack
  - mv demo-clang-release clang/demo
  - mv load_unit_gen-clang-release clang/load_unit_gen
  - mv pack_file_gen-clang-release clang/pack_file_gen
#  - mv assets-clang-release.pack clang/assets.pack
  - mv demo-msvc-release.exe msvc/demo.exe
  - mv load_unit_gen-msvc-release.exe msvc/load_unit_gen.exe
  - mv pack_file_gen-msvc-release.exe msvc/pack_file_gen.exe
#  - mv assets-msvc-release.pack msvc/assets.pack
  - mv demo-mingw-release.exe mingw/demo.exe
  - mv load_unit_gen-mingw-release.exe mingw/load_unit_gen.exe
  - mv pack_file_gen-mingw-release.exe mingw/pack_file_gen.exe
#  - mv assets-mingw-release.pack mingw/assets.pack
#  - sha1sum -b cloc_report.txt refman.pdf gcc/demo gcc/load_unit_gen gcc/pack_file_gen clang/demo clang/load_unit_gen clang/pack_file_gen msvc/demo.exe msvc/load_unit_gen.exe msvc/pack_file_gen.exe mingw/demo.exe mingw/load_unit_gen.exe mingw/pack_file_gen.exe gcc/assets.pack clang/assets.pack msvc/assets.pack mingw/assets.pack > checksums.txt
  - sha1sum -b cloc_report.txt refman.pdf gcc/demo gcc/load_unit_gen gcc/pack_file_gen clang/demo clang/load_unit_gen clang/pack_file_gen msvc/demo.exe msvc/load_unit_gen.exe msvc/pack_file_gen.exe mingw/demo.exe mingw/load_unit_gen.exe mingw/pack_file_gen.exe > checksums.txt
  - cat checksums.txt
  tags:
  - package
  artifacts:
    name: "mce_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}_${CI_BUILD_REF}"
    expire_in: 6 months
    paths:
    - refman.pdf
    - cloc_report.txt
    - gcc/demo
    - gcc/load_unit_gen
    - gcc/pack_file_gen
#    - gcc/assets.pack
    - clang/demo
    - clang/load_unit_gen
    - clang/pack_file_gen
#    - clang/assets.pack
    - msvc/demo.exe
    - msvc/load_unit_gen.exe
    - msvc/pack_file_gen.exe
#    - msvc/assets.pack
    - mingw/demo.exe
    - mingw/load_unit_gen.exe
    - mingw/pack_file_gen.exe
#    - mingw/assets.pack
    - checksums.txt
    - licenses

package-tags:
  stage: package
  only: 
    - tags
  script:
  - mkdir gcc
  - mkdir clang
  - mkdir msvc
  - mv demo-gcc-release gcc/demo
  - mv load_unit_gen-gcc-release gcc/load_unit_gen
  - mv pack_file_gen-gcc-release gcc/pack_file_gen
#  - mv assets-gcc-release.pack gcc/assets.pack
  - mv demo-clang-release clang/demo
  - mv load_unit_gen-clang-release clang/load_unit_gen
  - mv pack_file_gen-clang-release clang/pack_file_gen
#  - mv assets-clang-release.pack clang/assets.pack
  - mv demo-msvc-release.exe msvc/demo.exe
  - mv load_unit_gen-msvc-release.exe msvc/load_unit_gen.exe
  - mv pack_file_gen-msvc-release.exe msvc/pack_file_gen.exe
#  - mv assets-msvc-release.pack msvc/assets.pack
  - mv demo-mingw-release.exe mingw/demo.exe
  - mv load_unit_gen-mingw-release.exe mingw/load_unit_gen.exe
  - mv pack_file_gen-mingw-release.exe mingw/pack_file_gen.exe
#  - mv assets-mingw-release.pack mingw/assets.pack
#  - sha1sum -b cloc_report.txt refman.pdf gcc/demo gcc/load_unit_gen gcc/pack_file_gen clang/demo clang/load_unit_gen clang/pack_file_gen msvc/demo.exe msvc/load_unit_gen.exe msvc/pack_file_gen.exe mingw/demo.exe mingw/load_unit_gen.exe mingw/pack_file_gen.exe gcc/assets.pack clang/assets.pack msvc/assets.pack mingw/assets.pack > checksums.txt
  - sha1sum -b cloc_report.txt refman.pdf gcc/demo gcc/load_unit_gen gcc/pack_file_gen clang/demo clang/load_unit_gen clang/pack_file_gen msvc/demo.exe msvc/load_unit_gen.exe msvc/pack_file_gen.exe mingw/demo.exe mingw/load_unit_gen.exe mingw/pack_file_gen.exe > checksums.txt
  - cat checksums.txt
  tags:
  - package
  artifacts:
    name: "mce_${CI_BUILD_REF_NAME}_${CI_BUILD_ID}_${CI_BUILD_REF}"
    paths:
    - refman.pdf
    - cloc_report.txt
    - gcc/demo
    - gcc/load_unit_gen
    - gcc/pack_file_gen
#    - gcc/assets.pack
    - clang/demo
    - clang/load_unit_gen
    - clang/pack_file_gen
#    - clang/assets.pack
    - msvc/demo.exe
    - msvc/load_unit_gen.exe
    - msvc/pack_file_gen.exe
#    - msvc/assets.pack
    - mingw/demo.exe
    - mingw/load_unit_gen.exe
    - mingw/pack_file_gen.exe
#    - mingw/assets.pack
    - checksums.txt
    - licenses
