include_guard()

find_package(glm REQUIRED)
set_property(
	TARGET glm
	APPEND
	PROPERTY INTERFACE_COMPILE_DEFINITIONS
		GLM_FORCE_RADIANS 
		GLM_FORCE_SIZE_T_LENGTH
		GLM_FORCE_DEPTH_ZERO_TO_ONE
		GLM_ENABLE_EXPERIMENTAL
	)
set_property(
	TARGET glm
	APPEND
	PROPERTY INTERFACE_COMPILE_OPTIONS
		$<$<CXX_COMPILER_ID:MSVC>:/wd4201>
	)
